name: den beste sidan
favicon: null
layout_spectrum: 0.8001462260726839
typography_spectrum: 0.5903023243881762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3564212014898658
  lightness: 0.3211649376899004
  saturation: 0.4638152963016182
  rhythmicContrast: 0.513282360509038
purpose: []
